### ISSUE TITLE
Zotero 7 links don't work

### ISSUE THREAD

**Issue by MunGell** [vanakat/zotero-link#10]
Please note that there is ongoing regression in Zotero 7 beta, where `zotero://select/library/items/<item id>` don't open the corresponding item.

Check on the most up to date information here: https://forums.zotero.org/discussion/114667/zotero-7-beta-zotero-links-not-working

**Comment by jensenojs** [comment]
_Edited: Comment moved to https://github.com/vanakat/zotero-link/issues/11_

**Comment by MunGell** [comment]
This was fixed in Zotero 7, I can confirm links work in version 7.0.9-beta.3+ece595e79
