### ISSUE TITLE
Plugin doesn't work with Zotero 7 setup

### ISSUE THREAD

**Issue by MunGell** [vanakat/zotero-link#11]
_Originally posted by @jensenojs in https://github.com/vanakat/zotero-link/issues/10#issuecomment-2184057824_

<img width="456" alt="image" src="https://github.com/vanakat/zotero-link/assets/56761542/baecb54f-46cc-4cf1-b2bc-7b4ba5e2a37e">

emmm, and i can't use it and all.

i also installed zotero bridge, am i missed sth?
<img width="796" alt="image" src="https://github.com/vanakat/zotero-link/assets/56761542/259b309a-225a-43a1-94a8-270417270f98">

**Comment by MunGell** [comment]
@jensenojs I've moved your question into the new issue.

I have just tested plugins on your versions/setup and it works for me.

Could you please check if you have enabled Local API in Zotero 7? 

It's in `Zotero 7 > Settings > Advanced > Allow other applications on this computer to communicate with Zotero`

See screenshot below:
<img width="912" alt="Screenshot 2024-06-22 at 22 32 09" src="https://github.com/vanakat/zotero-link/assets/812976/eda12e1d-8c35-41df-8591-518250188256">

**Comment by MunGell** [comment]
_Originally posted by @jensenojs in https://github.com/MunGell/ZotServer/issues/5#issuecomment-2184059720_

@MunGell Thanks for your work. I wonder if zotero-link works with zotero7 now?

my obsidian version : Version 1.6.3 (Installer 1.4.13)
zotero version : 7.0.0-beta.91+3c6625f3c
zotero-brigde and zotero-link already update to latest, mac m2 air

![image](https://github.com/MunGell/ZotServer/assets/56761542/0306adfc-43ef-4fce-ac38-a0e00a63c303)

am i missed sth?

https://github.com/vanakat/zotero-link/issues/10#issuecomment-2184057824

**Comment by MunGell** [comment]
I've just updated README to add this installation prerequisite.

**Comment by jensenojs** [comment]
it works!
