### ISSUE TITLE
Doesn't work in Zotero 6

### ISSUE THREAD

**Issue by duduOliver** [vanakat/zotero-link#12]
Hello! Your plugin looks really interesting but, until now, it doesn't work on my side. 
I received the same error msg as the one in the following issue: https://github.com/vanakat/zotero-link/issues/11#issue-2368030909
I installed the ZotServer, zotero-bridge, zotero-link with no error. Feel free to let me know if you need any extra info.

**Comment by MunGell** [comment]
Hi @duduOliver 

The issue in https://github.com/vanakat/zotero-link/issues/11#issue-2368030909 is in Zotero 7 setup, which is different from what you have (Zotero 6, right?)

You need to go to Obsidian Settings, then select "Zotero Bridge" plugin in the left menu, and switch "Connection type" from Zotero 7 to Zotero 6.

Please let me know if this helps.

**Comment by duduOliver** [comment]
> Hi @duduOliver
> 
> The issue in [#11 (comment)](https://github.com/vanakat/zotero-link/issues/11#issue-2368030909) is in Zotero 7 setup, which is different from what you have (Zotero 6, right?)
> 
> You need to go to Obsidian Settings, then select "Zotero Bridge" plugin in the left menu, and switch "Connection type" from Zotero 7 to Zotero 6.
> 
> Please let me know if this helps.

Hi @MunGell !

Thanks for your reply! What I wanted to say is that I followed the corresponding plugin installation and configuration for the Zotero6 version, but still received the same error message as in the screenshot of this issue in [#11 (comment)](https://github.com/vanakat/zotero-link/issues/11#issue-2368030909) . 
My Zotero version is 6.0.36

**Comment by Neandertaletz** [comment]
> > Hi @duduOliver
> > The issue in [#11 (comment)](https://github.com/vanakat/zotero-link/issues/11#issue-2368030909) is in Zotero 7 setup, which is different from what you have (Zotero 6, right?)
> > You need to go to Obsidian Settings, then select "Zotero Bridge" plugin in the left menu, and switch "Connection type" from Zotero 7 to Zotero 6.
> > Please let me know if this helps.
> 
> Hi @MunGell !
> 
> Thanks for your reply! What I wanted to say is that I followed the corresponding plugin installation and configuration for the Zotero6 version, but still received the same error message as in the screenshot of this issue in [#11 (comment)](https://github.com/vanakat/zotero-link/issues/11#issue-2368030909) . My Zotero version is 6.0.36

I have the same problem

**Comment by MunGell** [comment]
Hi all, thank you for the details and sorry fro the wait.

It seems I had a mistake in code for Zotero 6, which should now be fixed (see https://github.com/vanakat/zotero-bridge/issues/11).

Fixed in version 1.6.3 of `zotero-bridge`

**Comment by MunGell** [comment]
I would really appreciate if you could let me know if this fixes it for you

**Comment by duduOliver** [comment]
Hi @MunGell !

I've just tested the 1.6.3 version of `zotero-bridge` and it looked all good! Thank you very much for the update!
