### ISSUE TITLE
Month value deviates by -1

### ISSUE THREAD

**Issue by yue-dongchen** [vanakat/zotero-link#15]
(Zotero 7 API)

`{{ date.month }}` seems to be zero-based, meaning the correct value is yielded only via `{{ date.month + 1 }}`. The day and year values are not zero-based.

**Comment by MunGell** [comment]
@dstillman is this a bug or should we account for this behavior in Zotero 7 local API client applications?

**Comment by dstillman** [comment]
What API are you referring to? JS Date month is 0-based.

**Comment by MunGell** [comment]
You are right, sorry for disturbance, issue is in this code.

Should be fixed in 1.6.4
