### ISSUE TITLE
Some characters in titles are not url decoded

### ISSUE THREAD

**Issue by jonasengelmann** [vanakat/zotero-link#17]
Thanks for this great plugin!

I have been using it now for a while and I noticed that some characters are not url decoded. For example title containing an apostrophe or an ampersand are still displayed in their url-escaped form, although they are correctly shown in the search window.

**Comment by MunGell** [comment]
Hi @jonasengelmann 

This is a limitation of the [templating engine](https://mozilla.github.io/nunjucks/api.html#renderstring), as a quick fix for your case you can use ["filters"](https://mozilla.github.io/nunjucks/templating.html#autoescaping) like this:

```
{{ title | safe }}
```

This way template engine will not escape characters and will output text as is.

I will work on finding a long-term fix for this, but this change in your template should be forward compatible.

**Comment by jonasengelmann** [comment]
Thanks for your answer and suggestion @MunGell, this works great!
