### ISSUE TITLE
about searching accuracy

### ISSUE THREAD

**Issue by ycbrd** [vanakat/zotero-link#2]
When I'm typing a keyword from the title of an item, it should be more convenient if the plugin provides the most accurate item at the top. Like:
 
![image](https://user-images.githubusercontent.com/105804326/182423635-3caee24a-1c10-4379-81c6-48a4c81c1f78.png)

The item I chose (and the following PDF) should be placed at the top, as they are the only 2 items in my library with the search word "misperc" in the title.

This is a very useful plugin for me and thanks a lot for your work.

**Comment by MunGell** [comment]
Hi @ycbrd 

Thank you very much for raising this issue, I will look into it as soon as I can

Related: https://github.com/vanakat/zotero-bridge/issues/5

**Comment by chxliou** [comment]
I would like to provide a simple fix for this issue.

step 1. goto `.obsidian\plugins\zotero-bridge\` you would see a file named `main.js`, right? open it.

step 2. find `quicksearch-everything` inside this file. 

step 3. replace it with `quicksearch-titleCreatorYear`

step 4. save, close and restart Obsidian

After these steps, your search accuracy would be increase, **however, limited in  title, creator and year fields** 

If you have solid javascript background, [see here](https://www.zotero.org/support/dev/client_coding/javascript_api#zotero_search_basics) to improve this plugin.

**Comment by MunGell** [comment]
Hi @chxliou 

Thank you for the brilliant idea, I will need to check if this approach and if it doesn't break common workflow might actually make this change in the plugin itself.
