### ISSUE TITLE
Links won't open (Linux issue?)

### ISSUE THREAD

**Issue by childeofentropy** [vanakat/zotero-link#4]
Hi, 

I installed everything and successfully linked pdfs but i am getting an error upon clicking on the link

![image](https://user-images.githubusercontent.com/29984745/208792162-a827288f-5880-4cea-835d-026be61ec482.png)

Is this relevant to my Zotero set-up or to my Linux OS? Any ideas for trouble shooting would be helpful

Thank you kindly for your work and time :)

**Comment by MunGell** [comment]
Hi @childeofentropy 

Sorry for the delay in response to your issue. It looks like Zotero is not associated to `zotero://` links in your OS. Unfortunately, I am not qualified to suggest exact steps to rectify the issue, but I hope that gives you something you can search the solution with.

**Comment by childeofentropy** [comment]
> Zotero is not associated to `zotero://` links in your OS

Thank you for your response. This will help me further troubleshoot the issue, maybe create an alias manually so redirecting to open links will work. If I am successful will post here for the archive. Have a nice day
