### ISSUE TITLE
Is it possible to show author and year in the preview?

### ISSUE THREAD

**Issue by noppelmax** [vanakat/zotero-link#7]
The search is already searching for author names as well, but the preview is only showing the title of the article. Is it possible to also show the First Author and the year next to the zotero id? Most often i'm not sure about the title but about the year of publication.

See screen shot:
![Screenshot from 2023-09-05 11-45-26](https://github.com/vanakat/zotero-link/assets/7629938/f78e4886-eaf6-4edb-b299-c3ee5d823e92)

**Comment by MunGell** [comment]
Hi @noppelmax 

This is implemented now in zotero-bridge version 1.6.0!

Thanks for your patience
