### ISSUE TITLE
After clicking on links created by zotero-link, anaconda navigator opens

### ISSUE THREAD

**Issue by JohannesWiesner** [vanakat/zotero-link#8]
Hi! I followed [this tutorial](https://curtismchale.ca/2023/05/24/creating-direct-links-to-zotero-documents-in-obsidian/) to create links with zotero-link within my markdown files that should forward me to the respective paper:

1) Add Zotero Bridge Addon in Obsidian
2) In Zotero add Zotserver
3) Add Zotero Link Addon in Obsidian

I can create links, but when I try to click on them Anaconda-Navigator opens instead of Zotero:

![Recording 2024-01-04 at 14 51 35](https://github.com/vanakat/zotero-link/assets/48254290/e4bb2833-d181-4afb-b873-42b88225c56b)

Perhaps [this thread](https://forum.obsidian.md/t/problem-opening-zotero-links/11613/5) and [this](https://forum.obsidian.md/t/problem-opening-zotero-links/11613/6) corresponding answer could be related? My current idea is that my machine currently does not know what to do with this link and then decides to use anaconda-navigator as the default application to open it?

I am using Ubuntu 22.04 and both Zotero and Obsidian were installed using Ansible.

**Comment by MunGell** [comment]
Hi @JohannesWiesner 

From what I can guess the problem is with your registered link handlers in Ubuntu.

Have a look here: https://askubuntu.com/questions/514125/url-protocol-handlers-in-basic-ubuntu-desktop
